"""Add avatar_url to users

Revision ID: 448ea15290f0
Revises: 
Create Date: 2025-06-02 18:41:08.933351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448ea15290f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
